apiVersion: v1
kind: ConfigMap
metadata:
  name: game-catalog-config
data:
  PORT: "8001"
  ORDER_SERVICE_URL: http://order-service:8003
  USER_SERVICE_URL: http://user-service:8002
  OTEL_SERVICE_NAME: game-catalog-service
