apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  PORT: "8003"
  CATALOG_SERVICE_URL: http://game-catalog-service:8001
  USER_SERVICE_URL: http://user-service:8002
  OTEL_SERVICE_NAME: order-service
  NODE_ENV: production
