parameters:
  - name: testResultsFormat
    type: string
  - name: testResultsFiles
    type: string
  - name: testRunTitle
    type: string
    default: 'Tests'
  - name: coverageTool
    type: string
  - name: coverageSummaryFile
    type: string
  - name: coverageReportDirectory
    type: string
    default: ''

steps:
  - task: PublishTestResults@2
    displayName: Publish test results
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: ${{ parameters.testResultsFormat }}
      testResultsFiles: ${{ parameters.testResultsFiles }}
      testRunTitle: ${{ parameters.testRunTitle }}

  - task: PublishCodeCoverageResults@2
    displayName: Publish code coverage
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: ${{ parameters.coverageTool }}
      summaryFileLocation: ${{ parameters.coverageSummaryFile }}
      reportDirectory: ${{ parameters.coverageReportDirectory }}
      failIfCoverageEmpty: true

