{{- if .Values.ingress.enabled }}
{{- $i := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ps-store.name" . }}
  labels: {{- include "ps-store.labels" (dict "ctx" . "component" "ingress") | nindent 4 }}
  {{- with $i.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $i.className }}
  {{- if $i.tls.enabled }}
  tls:
    - hosts:
        - {{ $i.host | quote }}
      secretName: {{ required "ingress.tls.secretName required when tls.enabled=true" $i.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ $i.host | quote }}
      http:
        paths:
          {{- if .Values.gameCatalogService.enabled }}
          - path: /api/games
            pathType: Prefix
            backend:
              service:
                name: game-catalog-service
                port:
                  number: {{ .Values.gameCatalogService.service.port }}
          - path: /api/categories
            pathType: Prefix
            backend:
              service:
                name: game-catalog-service
                port:
                  number: {{ .Values.gameCatalogService.service.port }}
          {{- end }}
          {{- if .Values.userService.enabled }}
          {{- range (list "/api/auth" "/api/users" "/api/wishlist" "/api/library") }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: {{ $.Values.userService.service.port }}
          {{- end }}
          {{- end }}
          {{- if .Values.orderService.enabled }}
          {{- range (list "/api/orders" "/api/cart") }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: {{ $.Values.orderService.service.port }}
          {{- end }}
          {{- end }}
          {{- if .Values.frontend.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          {{- end }}
{{- end }}
