apiVersion: v2
name: ps-store
description: PlayStation Store microservices (frontend + 3 backends + Postgres)
type: application
version: 0.1.0
appVersion: "1.0.0"
kubeVersion: ">=1.25.0-0"
keywords:
  - microservices
  - postgres
  - react
  - dotnet
  - fastapi
  - nodejs
maintainers:
  - name: ps-store
