# Production overrides — only deltas from values.yaml

ingress:
  tls:
    enabled: true
    secretName: ps-store-tls

postgres:
  resources:
    requests: { cpu: "500m", memory: "256Mi" }
    limits: { cpu: "2", memory: "1Gi" }

gameCatalogService:
  replicaCount: 3
  resources:
    requests: { cpu: "500m", memory: "256Mi" }
    limits: { cpu: "2", memory: "768Mi" }

userService:
  replicaCount: 3
  resources:
    requests: { cpu: "500m", memory: "256Mi" }
    limits: { cpu: "2", memory: "768Mi" }

orderService:
  replicaCount: 3
  resources:
    requests: { cpu: "500m", memory: "256Mi" }
    limits: { cpu: "2", memory: "768Mi" }

frontend:
  resources:
    requests: { cpu: "250m", memory: "128Mi" }
    limits: { cpu: "1", memory: "512Mi" }
