apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=user_db;Username=postgres;Password=postgres
  Jwt__Secret: change-me-in-production

